services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/snippets:/snippets:ro
    environment:
      TZ: "Europe/Berlin"
    networks:
      - appnet

  kong:
    ports: !reset [] # Disable Kong ports as we'll be doing this ourselves via our nginx setup
